version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: text2mermaid-backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      # Add Gemini API key from .env file or use a placeholder
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_key_here}
    restart: unless-stopped
    networks:
      - text2mermaid-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://backend:3001
    container_name: text2mermaid-frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - text2mermaid-network

# Define the network
networks:
  text2mermaid-network:
    driver: bridge
